package v1alpha1

import (
	github "github.com/google/go-github/v25/github"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubEvent) DeepCopyInto(out *GithubEvent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		if *in == nil {
			*out = nil
		} else {
			*out = new(string)
			**out = **in
		}
	}
	if in.Repo != nil {
		in, out := &in.Repo, &out.Repo
		if *in == nil {
			*out = nil
		} else {
			*out = new(github.Repository)
			**out = **in
		}
	}
	if in.Sender != nil {
		in, out := &in.Sender, &out.Sender
		if *in == nil {
			*out = nil
		} else {
			*out = new(github.User)
			**out = **in
		}
	}
	if in.PullRequest != nil {
		in, out := &in.PullRequest, &out.PullRequest
		if *in == nil {
			*out = nil
		} else {
			*out = new(github.PullRequest)
			**out = **in
		}
	}
	return
}
