/*
Copyright 2018 The KubeCI Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "kube.ci/git-apiserver/apis/repositories/v1alpha1"
	scheme "kube.ci/git-apiserver/client/clientset/versioned/scheme"
)

// BranchesGetter has a method to return a BranchInterface.
// A group's client should implement this interface.
type BranchesGetter interface {
	Branches(namespace string) BranchInterface
}

// BranchInterface has methods to work with Branch resources.
type BranchInterface interface {
	UpdateStatus(*v1alpha1.Branch) (*v1alpha1.Branch, error)
	Get(name string, options v1.GetOptions) (*v1alpha1.Branch, error)
	List(opts v1.ListOptions) (*v1alpha1.BranchList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	BranchExpansion
}

// branches implements BranchInterface
type branches struct {
	client rest.Interface
	ns     string
}

// newBranches returns a Branches
func newBranches(c *RepositoriesV1alpha1Client, namespace string) *branches {
	return &branches{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the branch, and returns the corresponding branch object, and an error if there is any.
func (c *branches) Get(name string, options v1.GetOptions) (result *v1alpha1.Branch, err error) {
	result = &v1alpha1.Branch{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("branches").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Branches that match those selectors.
func (c *branches) List(opts v1.ListOptions) (result *v1alpha1.BranchList, err error) {
	result = &v1alpha1.BranchList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("branches").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested branches.
func (c *branches) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("branches").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *branches) UpdateStatus(branch *v1alpha1.Branch) (result *v1alpha1.Branch, err error) {
	result = &v1alpha1.Branch{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("branches").
		Name(branch.Name).
		SubResource("status").
		Body(branch).
		Do().
		Into(result)
	return
}
