/*
Copyright 2018 The KubeCI Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kube.ci/git-apiserver/apis/repositories/v1alpha1"
)

// FakeBranches implements BranchInterface
type FakeBranches struct {
	Fake *FakeRepositoriesV1alpha1
	ns   string
}

var branchesResource = schema.GroupVersionResource{Group: "repositories.git.kube.ci", Version: "v1alpha1", Resource: "branches"}

var branchesKind = schema.GroupVersionKind{Group: "repositories.git.kube.ci", Version: "v1alpha1", Kind: "Branch"}

// Get takes name of the branch, and returns the corresponding branch object, and an error if there is any.
func (c *FakeBranches) Get(name string, options v1.GetOptions) (result *v1alpha1.Branch, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(branchesResource, c.ns, name), &v1alpha1.Branch{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Branch), err
}

// List takes label and field selectors, and returns the list of Branches that match those selectors.
func (c *FakeBranches) List(opts v1.ListOptions) (result *v1alpha1.BranchList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(branchesResource, branchesKind, c.ns, opts), &v1alpha1.BranchList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.BranchList{ListMeta: obj.(*v1alpha1.BranchList).ListMeta}
	for _, item := range obj.(*v1alpha1.BranchList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested branches.
func (c *FakeBranches) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(branchesResource, c.ns, opts))

}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBranches) UpdateStatus(branch *v1alpha1.Branch) (*v1alpha1.Branch, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(branchesResource, "status", c.ns, branch), &v1alpha1.Branch{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Branch), err
}
