/*
Copyright 2018 The KubeCI Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/kube-ci/git-apiserver/apis/git/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePullRequests implements PullRequestInterface
type FakePullRequests struct {
	Fake *FakeGitV1alpha1
	ns   string
}

var pullrequestsResource = schema.GroupVersionResource{Group: "git.kube.ci", Version: "v1alpha1", Resource: "pullrequests"}

var pullrequestsKind = schema.GroupVersionKind{Group: "git.kube.ci", Version: "v1alpha1", Kind: "PullRequest"}

// Get takes name of the pullRequest, and returns the corresponding pullRequest object, and an error if there is any.
func (c *FakePullRequests) Get(name string, options v1.GetOptions) (result *v1alpha1.PullRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(pullrequestsResource, c.ns, name), &v1alpha1.PullRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PullRequest), err
}

// List takes label and field selectors, and returns the list of PullRequests that match those selectors.
func (c *FakePullRequests) List(opts v1.ListOptions) (result *v1alpha1.PullRequestList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(pullrequestsResource, pullrequestsKind, c.ns, opts), &v1alpha1.PullRequestList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PullRequestList{ListMeta: obj.(*v1alpha1.PullRequestList).ListMeta}
	for _, item := range obj.(*v1alpha1.PullRequestList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested pullRequests.
func (c *FakePullRequests) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(pullrequestsResource, c.ns, opts))

}

// Create takes the representation of a pullRequest and creates it.  Returns the server's representation of the pullRequest, and an error, if there is any.
func (c *FakePullRequests) Create(pullRequest *v1alpha1.PullRequest) (result *v1alpha1.PullRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(pullrequestsResource, c.ns, pullRequest), &v1alpha1.PullRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PullRequest), err
}

// Update takes the representation of a pullRequest and updates it. Returns the server's representation of the pullRequest, and an error, if there is any.
func (c *FakePullRequests) Update(pullRequest *v1alpha1.PullRequest) (result *v1alpha1.PullRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(pullrequestsResource, c.ns, pullRequest), &v1alpha1.PullRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PullRequest), err
}

// Delete takes name of the pullRequest and deletes it. Returns an error if one occurs.
func (c *FakePullRequests) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(pullrequestsResource, c.ns, name), &v1alpha1.PullRequest{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePullRequests) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(pullrequestsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.PullRequestList{})
	return err
}

// Patch applies the patch and returns the patched pullRequest.
func (c *FakePullRequests) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.PullRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(pullrequestsResource, c.ns, name, data, subresources...), &v1alpha1.PullRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PullRequest), err
}
