/*
Copyright 2018 The KubeCI Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "kube.ci/git-apiserver/apis/git/v1alpha1"
	scheme "kube.ci/git-apiserver/client/clientset/versioned/scheme"
)

// RepositoryBindingsGetter has a method to return a RepositoryBindingInterface.
// A group's client should implement this interface.
type RepositoryBindingsGetter interface {
	RepositoryBindings(namespace string) RepositoryBindingInterface
}

// RepositoryBindingInterface has methods to work with RepositoryBinding resources.
type RepositoryBindingInterface interface {
	Create(*v1alpha1.RepositoryBinding) (*v1alpha1.RepositoryBinding, error)
	Update(*v1alpha1.RepositoryBinding) (*v1alpha1.RepositoryBinding, error)
	UpdateStatus(*v1alpha1.RepositoryBinding) (*v1alpha1.RepositoryBinding, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.RepositoryBinding, error)
	List(opts v1.ListOptions) (*v1alpha1.RepositoryBindingList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.RepositoryBinding, err error)
	RepositoryBindingExpansion
}

// repositoryBindings implements RepositoryBindingInterface
type repositoryBindings struct {
	client rest.Interface
	ns     string
}

// newRepositoryBindings returns a RepositoryBindings
func newRepositoryBindings(c *GitV1alpha1Client, namespace string) *repositoryBindings {
	return &repositoryBindings{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the repositoryBinding, and returns the corresponding repositoryBinding object, and an error if there is any.
func (c *repositoryBindings) Get(name string, options v1.GetOptions) (result *v1alpha1.RepositoryBinding, err error) {
	result = &v1alpha1.RepositoryBinding{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("repositorybindings").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of RepositoryBindings that match those selectors.
func (c *repositoryBindings) List(opts v1.ListOptions) (result *v1alpha1.RepositoryBindingList, err error) {
	result = &v1alpha1.RepositoryBindingList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("repositorybindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested repositoryBindings.
func (c *repositoryBindings) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("repositorybindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a repositoryBinding and creates it.  Returns the server's representation of the repositoryBinding, and an error, if there is any.
func (c *repositoryBindings) Create(repositoryBinding *v1alpha1.RepositoryBinding) (result *v1alpha1.RepositoryBinding, err error) {
	result = &v1alpha1.RepositoryBinding{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("repositorybindings").
		Body(repositoryBinding).
		Do().
		Into(result)
	return
}

// Update takes the representation of a repositoryBinding and updates it. Returns the server's representation of the repositoryBinding, and an error, if there is any.
func (c *repositoryBindings) Update(repositoryBinding *v1alpha1.RepositoryBinding) (result *v1alpha1.RepositoryBinding, err error) {
	result = &v1alpha1.RepositoryBinding{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("repositorybindings").
		Name(repositoryBinding.Name).
		Body(repositoryBinding).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *repositoryBindings) UpdateStatus(repositoryBinding *v1alpha1.RepositoryBinding) (result *v1alpha1.RepositoryBinding, err error) {
	result = &v1alpha1.RepositoryBinding{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("repositorybindings").
		Name(repositoryBinding.Name).
		SubResource("status").
		Body(repositoryBinding).
		Do().
		Into(result)
	return
}

// Delete takes name of the repositoryBinding and deletes it. Returns an error if one occurs.
func (c *repositoryBindings) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("repositorybindings").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *repositoryBindings) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("repositorybindings").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched repositoryBinding.
func (c *repositoryBindings) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.RepositoryBinding, err error) {
	result = &v1alpha1.RepositoryBinding{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("repositorybindings").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
