/*
Copyright 2018 The KubeCI Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	git_v1alpha1 "kube.ci/git-apiserver/apis/git/v1alpha1"
	versioned "kube.ci/git-apiserver/client/clientset/versioned"
	internalinterfaces "kube.ci/git-apiserver/client/informers/externalversions/internalinterfaces"
	v1alpha1 "kube.ci/git-apiserver/client/listers/git/v1alpha1"
)

// RepositoryBindingInformer provides access to a shared informer and lister for
// RepositoryBindings.
type RepositoryBindingInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.RepositoryBindingLister
}

type repositoryBindingInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewRepositoryBindingInformer constructs a new informer for RepositoryBinding type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewRepositoryBindingInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredRepositoryBindingInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredRepositoryBindingInformer constructs a new informer for RepositoryBinding type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredRepositoryBindingInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GitV1alpha1().RepositoryBindings(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GitV1alpha1().RepositoryBindings(namespace).Watch(options)
			},
		},
		&git_v1alpha1.RepositoryBinding{},
		resyncPeriod,
		indexers,
	)
}

func (f *repositoryBindingInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredRepositoryBindingInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *repositoryBindingInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&git_v1alpha1.RepositoryBinding{}, f.defaultInformer)
}

func (f *repositoryBindingInformer) Lister() v1alpha1.RepositoryBindingLister {
	return v1alpha1.NewRepositoryBindingLister(f.Informer().GetIndexer())
}
